### ISSUE TITLE
List the members of the batch (read OnbardingBatch contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch5.buidlguidl.com#3]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #9 )
- Each builder should link to their personal profile (see #8)

**Comment by zapaz** [comment]
where to find the `OnbardingBatch` contract ?

**Comment by zapaz** [comment]
> where to find the `OnbardingBatch` contract ?

I did used  `EventLogs` instead,   preview result [here](https://batch5-buidlguidl-com-nextjs-git-fork-zapa-f468b7-buidlguidldao.vercel.app/builders)
