### ISSUE TITLE
Get the check-in count from the Batch Registry contract

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch5.buidlguidl.com#5]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: https://github.com/BuidlGuidl/batch5.buidlguidl.com/issues/9

**Comment by ishaan812** [comment]
Can I pick this up?

**Comment by cleanerzkp** [comment]
can help you out @ishaan812

**Comment by ishaan812** [comment]
Hey @cleanerzkp seems like a super easy task actually. just using the read contract scaffold hook and use it to show the variable. Just a couple lines of code. 

`import { useScaffoldReadContract } from "~~/hooks/scaffold-eth/useScaffoldReadContract";

const Home: NextPage = () => {
  const { data: checkedInCount, isFetched: checkedInCountFetched } = useScaffoldReadContract({
    contractName: "BatchRegistry",
    functionName: "checkedInCounter",
  });
  `
  like this I think.

**Comment by derrekcoleman** [comment]
Closed by #19
